name: Deploy to AWS EC2

on:
  push:
    branches: [ main ]  # Change "main" if you use another branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "."
          target: "/var/www/html/"
          overwrite: true
          rm: true  # Optional, see below


